### ISSUE TITLE
Compatibility with Contiki 3.0

### ISSUE THREAD

**Issue by DavidAngc** [msloth/RWMMSim#1]
Hi,
Thanks for sharing the mobility code.
I have tried this plugin in Contiki 2.7 and it works very well.
However, when i try to do it in Contiki 3.0, it is not successful.

Is it possible to provide guidance on how to do mobility in Contiki 3.0?

Thanks.

**Comment by msloth** [comment]
Sorry, I'm not maintaining this. Check with the contiki developers/users list or have a go at it yourself. Best of luck,
M
